name: .NET CI/CD

on:
  push:
    branches: [ DevOps ]
  pull_request:
    branches: [ DevOps ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore Backend/Codience.sln

      - name: Build
        run: dotnet build Backend/Codience.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test Backend/Codience.sln --no-build --verbosity normal

      - name: Build Docker Image
        run: |
          docker build -t codience:latest Backend/

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image
        run: docker tag codiencelatest shahdelnassag/codience:latest
      - run: docker push shahdelnassag/codience:latest
